version: '3.8'

services:
  backend:
    image: amirjab121/mlx-backend:latest
    ports:
      - "8000:8000"
    container_name: fastapi-backend-prod
    restart: unless-stopped
    environment:
      - ENVIRONMENT=production

  frontend:
    image: amirjab121/mlx-frontend:latest
    ports:
      - "80:80"
    container_name: react-frontend-prod
    restart: unless-stopped
    depends_on:
      - backend 